import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  skill: [
    'skill/introduction',
    {
      label: 'Docusaurus 主题魔改',
      type: 'category',
      link: {
        type: 'doc',
        id: 'skill/docusaurus/docusaurus-guides',
      },
      items: [
        'skill/docusaurus/docusaurus-config',
        'skill/docusaurus/docusaurus-style',
        'skill/docusaurus/docusaurus-component',
        'skill/docusaurus/docusaurus-plugin',
        'skill/docusaurus/docusaurus-search',
        'skill/docusaurus/docusaurus-comment',
        'skill/docusaurus/docusaurus-deploy',
      ]
    }
  ],
  seo: [
    'seo/introduction',
    {
      label: '哥飞小课堂',
      type: 'category',
      link: {
        type: 'doc',
        id: 'seo/miniclass/miniclass',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'seo/miniclass',
        },
      ],
    },
    {
      label: '日常分享',
      type: 'category',
      link: {
        type: 'doc',
        id: 'seo/dailyshare/dailyshare',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'seo/dailyshare',
        },
      ],
    },
    {
      label: '新词分析',
      type: 'category',
      link: {
        type: 'doc',
        id: 'seo/newwords/introduction',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'seo/newwords',
        },
      ],
    },
    {
      label: '新站测评',
      type: 'category',
      link: {
        type: 'doc',
        id: 'seo/newwebsites/introduction',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'seo/newwebsites',
        },
      ],
    }
  ]
}

module.exports = sidebars
